version: '3.9'
services:
  app:
    build: .
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
    environment:
      DB_DSN: mongodb://root:password@mongo:27017/?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodata:/data/db
